### ISSUE TITLE
MAX31855 or MAX6675?

### ISSUE THREAD

**Issue by goosenphil** [foxis/ESPReflow#2]
The README.md claims you are using the MAX6675, but the schematic shows a MAX31855 instead. Which one are you using?

**Comment by goosenphil** [comment]
Upon inspecting the code I have found that it uses a library for the MAX6675. Are you planning on updating the software for the new schematic? (Or just make an option to select which sensor at build time with an ifdef)

**Comment by foxis** [comment]
I am waiting for the boards to arrive. After soldering I'll update the code accordingly. Currently the code won't work with the schematics at all due to the way led and power control signals are implemented.
