### ISSUE TITLE
Unable to read config and profiles json files

### ISSUE THREAD

**Issue by 3daerovision** [foxis/ESPReflow#7]
Hi,
I have succesfully uploaded the project to my board, but once it starts, it can't open the config.json and profiles.json files, and it doesn't take the wifi config into account. Any idea of the problem ?

Here is the startup log :

> Loading config /config.json; Heap: 37632
> Could not open config file
> Loading config /profiles.json; Heap: 37632
> Could not open config file
> OTA setup
> WARNING: No PID named 'default' found!!
> Current temperature: 0.000000
> 
> Controller setup..
> Controller setup DONE
> Server started..
> Reflow Controller v1.0 Initialized and ready
> Change mode: from Init to OFF
> OTA message: Wifi scan

My board is a Wemos D1, so I modified the configuration in the code, according to the change made for your board.
I didn't compiled the front as it seems to already be in the web folder.
Thanks,
Tristan

**Comment by foxis** [comment]
Hello,

Have you flashed SPIFFS too?

---
What new shall I learn today?

**Comment by 3daerovision** [comment]
I'm new to PlatformIO, and I didn't saw I had to upload the filesystem too. Doing this solve the issue for the json files, but it still doesn't connect to my wifi as set in the wificonfig.h. Is there a way to specify the wifi config in the config.json file ?

**Comment by 3daerovision** [comment]
I modified the code to force it to AP, and finally get access to the UI, thanks !
